# platform :ios, '13.0'

target 'Runar' do

  # Pods for Runar
  use_frameworks!
  pod 'SwiftGen'
  pod 'SnapKit'
  pod 'KTCenterFlowLayout'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  target 'RunarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunarUITests' do
    # Pods for testing
  end

end
