platform :ios, '13.0'
workspace 'Runar'

target 'Runar' do

  # Pods for Runar
  use_frameworks!
  pod 'SwiftGen', '~> 6.6'
  pod 'SnapKit'
  pod 'KTCenterFlowLayout'

  target 'RunarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
